#Flujo para ejecutar un build de produccion (rama main)
#En Netlify con el proposito de que nuestro 
#contenido se actualice

name: Trigger Netlify Build

  on:
    schedule:
    #You can use https://crontab.guru to generate the desired cron scheduled
      - cron: '10 * * * *' # At 10:00 on Monday

  jobs:
    build:
      name: Request Netlify Build
      runs-on: ubuntu-latest
      steps:
        name: Ping
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/61e1aa8c6a0e263a5f33d6ad